export const projectsConfig = {
  projects: [
    {
      id: 1,
      title: 'AttentionPlay',
      shortDescription: 'Transformer-based deep learning system for playlist continuation and music recommendation.',
      fullDescription: 'Recommendation pipeline using transformer architectures for personalized playlist generation.',
      thumbnail: '/assets/project_assets/1.png',
      technologies: ['Transformers', 'Deep Learning', 'Recommendation Systems'],
      skills: ['Python', 'PyTorch', 'TensorFlow', 'Pandas', 'NumPy', 'Git'],
      category: 'Recommender Systems',
      links: { live: null, github: 'https://github.com/Virum9520/AttentionPlay-Transformer-Based_Deep_Learning_Playlist_Recommendation_System#readme' },
      featured: true,
    },
    {
      id: 2,
      title: 'Big Data Pipeline using AWS',
      shortDescription: 'Scalable cloud pipeline for processing high-volume, high-variety datasets.',
      fullDescription: 'End-to-end data engineering pipeline for ingestion, transformation, and cloud-scale processing.',
      thumbnail: '/assets/project_assets/2.png',
      technologies: ['AWS', 'ETL', 'Big Data'],
      skills: ['AWS', 'Python', 'Spark', 'Docker', 'SQL', 'GitHub Actions'],
      category: 'Data Engineering',
      links: { live: null, github: 'https://github.com/Virum9520/Big-Data-Pipeline-using-AWS#readme' },
      featured: true,
    },
    {
      id: 3,
      title: 'EEG-based ML Model for Autism Detection',
      shortDescription: 'EEG signal classification system for autism detection and severity-oriented analysis.',
      fullDescription: 'Machine learning workflow over EEG features for classification and exploratory severity clustering.',
      thumbnail: '/assets/project_assets/3.png',
      technologies: ['EEG', 'CNN', 'LSTM', 'ML'],
      skills: ['Python', 'PyTorch', 'TensorFlow', 'NumPy', 'Pandas', 'Scikit-learn'],
      category: 'Healthcare AI',
      links: { live: null, github: 'https://github.com/Virum9520/EEG-based-Machine-Learning-model-for-Autism-detection-and-severity-analysis#readme' },
      featured: true,
    },
    {
      id: 4,
      title: 'MultiAgent Stock Analysis Using CrewAI',
      shortDescription: 'Multi-agent investment research workflow using CrewAI for stock analysis.',
      fullDescription: 'Agent-based system orchestrating analysis roles for stock research and summarized insights.',
      thumbnail: '/assets/project_assets/4.png',
      technologies: ['CrewAI', 'LLM Agents', 'Finance'],
      skills: ['Python', 'CrewAI', 'LLM Orchestration', 'Prompt Engineering', 'Git'],
      category: 'AI Agents',
      links: {
        live: 'https://multiagent-stockanalysis-using-crewai.onrender.com/',
        github: 'https://github.com/Virum9520/MultiAgent-StockAnalysis-Using-CrewAI#readme',
      },
      featured: true,
    },
    {
      id: 5,
      title: 'Flex.i - AI Powered Fitness Web Application',
      shortDescription: 'AI-assisted fitness web app for workout planning and guided progress tracking.',
      fullDescription: 'Fitness-focused web app combining AI-assisted planning with a responsive product experience.',
      thumbnail: '/assets/project_assets/5.png',
      technologies: ['Web App', 'AI', 'Fitness'],
      skills: ['JavaScript', 'React', 'Node.js', 'API Integration', 'Git'],
      category: 'AI Product Engineering',
      links: { live: null, github: 'https://github.com/Virum9520/Flex.i-AI-powered-fitness-Web-application#readme' },
      featured: true,
    },
  ],
  categories: ['All', 'AI Product Engineering', 'Recommender Systems', 'Data Engineering', 'Healthcare AI', 'AI Agents'],
};
